services:
  - type: web
    plan: free
    name: Auto
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Doctorstra/Auto.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: START_PIC
        sync: false
      - key: AUTH_USERS
        sync: false
      - key: WEBHOOK
        sync: false
      - key: COLLECTION_NAME
        sync: false 

